---

name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  ok:
    runs-on: ubuntu-24.04
    needs:
      - test-lint
    if: failure()
    steps:
      - run: exit 1
  test-lint:
    strategy:
      matrix:
        go_version:
          - oldstable
          - stable
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: read
      pull-requests: write
    env:
      AQUA_CONFIG: ${{ github.workspace }}/aqua.yaml
      AQUA_POLICY_CONFIG: ${{ github.workspace }}/aqua-policy.yaml
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        id: setup-go
        with:
          go-version: ${{ matrix.go_version }}
      - run: go mod download
      - name: build
        run: |
          go build -o /dev/null ./...
      - name: test
        id: test
        run: go test -v -race -coverprofile=cover.out -covermode=atomic ./...
      - uses: k1LoW/octocov-action@1ad702b3118b6a055c00b01db68ca0d9f6641dbc # v1.4.0
        if: ${{ matrix.go_version == 'stable' && steps.test.outcome == 'success' }}
      - uses: aquaproj/aqua-installer@5e54e5cee8a95ee2ce7c04cb993da6dfad13e59c # v3.1.2
        with:
          aqua_version: v2.43.3
      - run: aqua install
      - name: golangci-lint
        env:
          _go_version: ${{ steps.setup-go.outputs.go-version }}
        run: |
          golangci-lint run \
            --go "$_go_version" \
            --out-format line-number \
            --issues-exit-code 0 \
            --config .golangci.yml \
            1>lint-stdout.txt 2>/dev/stderr
      - name: reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
        run: |
          reviewdog \
            -name golangci-lint \
            -f golangci-lint \
            -filter-mode nofilter \
            -reporter github-pr-check \
            -fail-level warning \
            < lint-stdout.txt
  determine_release:
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/main'
    outputs:
      will_release: ${{ steps.determine_release.outputs.new_release_published }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - id: determine_release
        uses: cycjimmy/semantic-release-action@16ca923e6ccbb50770c415a0ccd43709a8c5f7a4 # v4.2.2
        with:
          dry_run: true
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
  release:
    runs-on: ubuntu-24.04
    needs:
      - test-lint
      - determine_release
    if: ${{ needs.determine_release.outputs.will_release }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: cycjimmy/semantic-release-action@16ca923e6ccbb50770c415a0ccd43709a8c5f7a4 # v4.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: 'stable'
      - uses: goreleaser/goreleaser-action@90a3faa9d0182683851fbfa97ca1a2cb983bfca3 # v6.2.1
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ github.token }}
